# Generated by Django 4.0.4 on 2022-05-18 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='tb_transactions',
        ),
    ]
